### ISSUE TITLE
Stuck builds

### ISSUE THREAD

**Issue by blitz** [nixbuild/feedback#2]
**Oberservation:**

I have observed one of my builds to get stuck.

```
build flags: -j16 -l16 SHELL=/nix/store/hrpvwkjz04s9i4nmli843hyw9z4pwhww-bash-4.4-p23/bin/bash profiledir=\$\(out\)/etc/profile.d
  GEN    Makefile.config                                                                       
  CXX    src/build-remote/build-remote.o                                                       
  CXX    src/nix-build/nix-build.o                                                             
  CXX    src/nix-channel/nix-channel.o                                                         
  CXX    src/nix-collect-garbage/nix-collect-garbage.o                                         
  CXX    src/nix-copy-closure/nix-copy-closure.o                                               
  CXX    src/nix-daemon/nix-daemon.o                                                           
  CXX    src/nix-env/nix-env.o                                                                 
  CXX    src/nix-env/user-env.o                                                                
  CXX    src/nix-instantiate/nix-instantiate.o                                                 
  CXX    src/nix-prefetch-url/nix-prefetch-url.o                                               
  CXX    src/nix-store/dotgraph.o                                                              
  CXX    src/nix-store/graphml.o                                                               
  CXX    src/nix-store/nix-store.o                                                             
  CXX    src/nix/add-to-store.o                                                                
  CXX    src/nix/build.o                                                                       
  CXX    src/nix/cat.o                                                                         

[... many minutes pass without output ...]                                                                                               

^C                                                                                             
error: interrupted by the user          
```

The shell still reports it as running:

```
72738 2020-08-31 13:28:03Z 39:27 16 CPUs [Running] 
      /nix/store/cbpjsi31awdpspjzfhxwd1w05fb2v0vc-nix-2.3.6.drv
```

After manually aborting it and restarting it, the job succeeded:

```
72766 2020-08-31 14:01:19Z 06:10 16 CPUs [Built] 
      /nix/store/cbpjsi31awdpspjzfhxwd1w05fb2v0vc-nix-2.3.6.drv
```

**Expected behavior**:

Builds succeed or get visibly aborted.

**Comment by rickynils** [comment]
@blitz We've noticed this behavior too, and we haven't figured the exact reason behind builds sometimes get stuck in this way (it doesn't happen very often, and we haven't been able to figure out a pattern. As you say, after the build is started again, it usually works). However, we have deployed some counter-measures to handle these situations. We actually deployed the first fixes just a day or two after you reported this issue. We haven't seen any builds get stuck since then.

So far, we've added this:

* An improved sandbox watchdog that can detect if the sandbox completely locks up for some reason, and restart the build. This should likely cover your case.

* Explicit checks of build timeouts and silent timeouts, instead of only relying on Nix catching those timeouts

* Upper caps on build timeouts and silent timeouts. Nix allows waiting indefinitely if timeouts are set to zero. We're now capping build timeouts to 12 hours.

I should also point out that when builds fail transiently like this, we restart them automatically and you're not billed for the restarted build. The only thing you notice is that the log output might repeat itself after the restart.

I'm closing this issue, but feel free re-opening it if you ever notice this behavior again.
