### ISSUE TITLE
Transient build error, unclear what to do

### ISSUE THREAD

**Issue by michaelpj** [nixbuild/feedback#25]
```
[nixbuild.net] Transient build error detected, but no more restarts are allowed. Please contact support@nixbuild.net.
```

- I'm unsure that you actually want me to email you about this, is it a big deal? not sure.
- I wouldn't know what information to include anyway, I don't have a build ID at this point. Maybe it could be printed?
- TBH, I would assume that your monitoring would tell you about this without me having to email you.

**Comment by rickynils** [comment]
If a build fails transiently over and over again, it is likely due to a bug in nixbuild.net, some issues in our infrastructure or something exceptionally weird about the particular build. I think we should merge these kinds of errors into #26, and have a better message (with build id etc, as you mention).

I will close this issue and handle it in #26.
