### ISSUE TITLE
Assertion `store->isValidPath(outPath)' failed

### ISSUE THREAD

**Issue by michaelpj** [nixbuild/feedback#29]
Unsure if this is a Nix bug or a nixbuild.net bug:

```
nix: src/nix/develop.cc:245: nix::StorePath getDerivationEnvironment(nix::ref<nix::Store>, nix::ref<nix::Store>, const nix::StorePath&): Assertion `store->isValidPath(outPath)' failed.
/home/runner/work/_temp/f8bf9b68-4291-43ba-985a-af3f6570ba20.sh: line 1:  2163 Aborted                 (core dumped) nix develop --eval-store auto --store ssh-ng://eu.nixbuild.net --max-jobs 2 --builders "" -c ./scripts/check.sh
```

Same command seems to work locally.

**Comment by rickynils** [comment]
Have you tested this with some other Nix machine as remote store? I suspect it won't work, since the `develop` command starts its shell locally, and the build inputs have likely only been realised in the remote store.
The error message from Nix could be nicer in this case.

**Comment by michaelpj** [comment]
Ah, I see. So `nix develop` fundamentally won't work with remote store builds?

In fact, something weird happened locally also, in that it seemed to just build it locally and ignore the remote store args. So I'm generally confused.

**Comment by rickynils** [comment]
I guess it _could_ work by first building in the remote store and then fetching the required output, but then I guess you could just use a remote builder instead. I don't have much experience of `nix develop`, but the main purpose of it should be to start a shell, and then you have to have the stuff locally. If there is a situation where using a remote store for `nix develop` could be more efficient than using a remote builder, then I guess this could be implemented in Nix, otherwise this combination of develop+remote store should just be forbidden in a more instructive way than throwing that assertion error.

**Comment by michaelpj** [comment]
Yeah, it makes sense, I think Nix should just give a better error!

**Comment by michaelpj** [comment]
Opened https://github.com/NixOS/nix/issues/8169
