### ISSUE TITLE
Sharing builds with uploaded artifacts

### ISSUE THREAD

**Issue by anka-213** [nixbuild/feedback#3]
In [this blog post](https://blog.nixbuild.net/posts/2020-08-13-build-reuse-in-nixbuild-net.html) you mention that builds based on uploaded inputs won't be shared.

My question is: If two users would build the same derivation and independently upload identical inputs (i.e. with the same content hash), would those builds be shared? It should be completely safe as far as I can tell. 

If the nix protocol allows it, you might even be able to avoid uploading the input at all for the second user, by asking for the hash before receiving the contents of the input.

**Comment by rickynils** [comment]
> My question is: If two users would build the same derivation and independently upload identical inputs (i.e. with the same content hash), would those builds be shared? It should be completely safe as far as I can tell.

Yes, such builds will be shared. The scenario you describe is explained in the same blog post, in the "Derivation Sharing" section. As you say, sharing builds in that case is completely safe since all inputs (and the derivation) is identical.

> If the nix protocol allows it, you might even be able to avoid uploading the input at all for the second user, by asking for the hash before receiving the contents of the input.

As the protocol looks now we need to receive the nar contents, even though we already have it. We simply flush it on our side, without any processing. I haven't yet looked in detail if this can be improved (in backwards-compatible way) in Nix.

**Comment by anka-213** [comment]
Oh, right. Thanks. I should have read the blog post more closely. I got stuck on the "No shared uploads" headline.

But, yes, it is indeed interesting if it would be possible to avoid re-uploading identical NARs.
