### ISSUE TITLE
`show build` doesn't actually show build details

### ISSUE THREAD

**Issue by yu-re-ka** [nixbuild/feedback#4]
```
nixbuild.net> show build 308804
308804
nixbuild.net> 
```

I would expect the same or a greater amount of detail than `list builds`

**Comment by rickynils** [comment]
Yes, this functionality is unfortunately missing in the shell. We are currently focusing on launching an HTTP API that will provide information on builds and other things, and when that is available, we will synchronize the shell with it so that `show build` (or some similarly named command) works as expected.

**Comment by rickynils** [comment]
We've finally launched the API that allows for getting detailed information on your builds, see https://docs.nixbuild.net/api-usage/. We will replace the `show build` shell command with something that reflects the API structure (so likely something like `builds --build-id 308804`) and returns the same info

**Comment by rickynils** [comment]
The `show` and `list` commands have been removed. We now have `builds list`, and there will also be `builds` sub commands for build info and summaries (corresponding to the API functionality).
