### ISSUE TITLE
Race condition (?) in remote store building

### ISSUE THREAD

**Issue by danth** [nixbuild/feedback#9]
Occasionally when using remote store building I get errors like:

```
error: [nixbuild.net] '/nix/store/«nixos-system».drv': dependency failed
       '/nix/store/«etc».drv': build not possible: /nix/store/«etc».drv: invalid derivation: invalid inputs: /nix/store/«user-units» /nix/store/«system-units»
```

Re-running the build allows it to complete successfully.

My best guess is that the `etc` derivation is starting to build before `user-units` and `system-units` have been fully committed to whatever store backend you're using.

This happens with a NixOS configuration, especially in the later stages where there is a lot of writing/symlinking of small files going on. It's not always the exact derivations listed above which fail.

**Comment by rickynils** [comment]
Thank you for confirming my suspicion about this bug! I've run into it a couple of times too, but not managed to reproduce it reliably. I think you are correct in your analysis. For some reason it seems a build under some circumstances can be started before its inputs have been built (or registered). I will see if I can reproduce and fix this bug.

**Comment by rickynils** [comment]
I believe this is fixed now. It wasn't a race condition but a logical error in the remote store builder code. If two or more builds was depending on an already running build, it could happen that we simply didn't build the rest of the inputs for those builds, due to a missing recursive call in our build function. I have corrected the code and has not been able to reproduce the issue after that.

@danth I'll leave this issue open until you're confident the issue is gone for you too.

**Comment by danth** [comment]
Hi, this seems to be working correctly now.

Thanks!
